apiVersion: apps/v1
kind: Deployment
metadata:
  name: restarter-operator
  namespace: restarter-operator
  labels:
    application: restarter-operator
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: restarter-operator
  template:
    metadata:
      labels:
        app: restarter-operator
    spec:
      serviceAccountName: restarter-operator
      securityContext:
        runAsUser:
          1000
      containers:
      - env:
        - name: VERBOSE
          value: "false"
        - name: DEBUG
          value: "false"
        - name: NAMESPACE
          value: ALL
        - name: LIVENESS
          value: "true"
        - name: LOOP_INTERVAL
          value: "60"
        - name: EXCLUDED_NAMESPACES
          value: "kube-system,kube-public,kube-node-lease,argocd,cert-manager,gatekeeper-system,gitlab,sonarqube,metallb-system,cluster-operators,monitoring,rook-ceph,ingress-controller" 
        name: op
        image: djkormo/restarter-op:latest
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 15
          failureThreshold: 30
          periodSeconds: 10
        securityContext:
          readOnlyRootFilesystem: true