apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: shutdown-operator-rolebinding-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: shutdown-operator-role-cluster
subjects:
  - kind: ServiceAccount
    name: shutdown-operator
    namespace: shutdown-operator
