apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: shutdown-operator-role-cluster
rules:

  # Framework: knowing which other operators are running (i.e. peering).
  - apiGroups: [kopf.dev]
    resources: [clusterkopfpeerings]
    verbs: [list, watch, patch, get]

  # Framework: runtime observation of namespaces & CRDs (addition/deletion).
  - apiGroups: [apiextensions.k8s.io]
    resources: [customresourcedefinitions]
    verbs: [list, watch]
  - apiGroups: [""]
    resources: [namespaces]
    verbs: [list, watch]

  # Framework: admission webhook configuration management.
  - apiGroups: [admissionregistration.k8s.io/v1, admissionregistration.k8s.io/v1beta1]
    resources: [validatingwebhookconfigurations, mutatingwebhookconfigurations]
    verbs: [create, patch]

  - apiGroups: [""]
    resources: [events]
    verbs: [create]

  # Application: read-only access for watching cluster-wide.
  - apiGroups: [djkormo.github]
    resources: [shutdowns,shutdowns/status]
    verbs: [list, watch,patch]
  # for controlling namespace  
  - apiGroups: [""]
    resources: [namespaces]
    verbs: [list, watch,patch]
  # for reading replicasets , deployments,statefulsets,daemonsets
  - apiGroups: ["apps",""]
    resources: [replicasets,deployments,deployments/scale,statefulsets,statefulsets/scale,daemonsets]
    verbs: [get,list, watch,patch]
