apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-operator
  namespace: project-operator
  labels:
    app: project-operator
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: project-operator
  template:
    metadata:
      labels:
        app: project-operator
    spec:
      serviceAccountName: project-operator
      securityContext:
        runAsUser:
          1000
      containers:
      - env:
        - name: VERBOSE
          value: "false"
        - name: DEBUG
          value: "false"
        - name: NAMESPACE
          value: ALL
        - name: LIVENESS
          value: "true"
        - name: LOOP_INTERVAL
          value: "60"
        - name: EXCLUDED_NAMESPACES
          value: "kube-system,kube-public,kube-node-lease"
        name: op
        image: djkormo/op-project
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - all
          privileged: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
