apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: primers.djkormo.github
spec:
  group: djkormo.github
  names:
    kind: Primer
    listKind: PrimerList
    plural: primers
    singular: primer
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: true
    subresources:
      status: {}