apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: primer-operator-rolebinding-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: primer-operator-role-cluster
subjects:
  - kind: ServiceAccount
    name: primer-operator
    namespace: primer-operator
