apiVersion: apps/v1
kind: Deployment
metadata:
  name: limitrange-np-operator
  namespace: project-operator
  labels:
    application: limitrange-np-operator
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: limitrange-np-operator
  template:
    metadata:
      labels:
        app: limitrange-np-operator
    spec:
      serviceAccountName: limitrange-np-operator
      securityContext:
        runAsUser:
          1000
      containers:
      - env:
        - name: VERBOSE
          value: "true"
        - name: DEBUG
          value: "true"
        - name: NAMESPACE
          value: project-operator
        - name: LIVENESS
          value: "true"
        name: op
        image: djkormo/op-limitrange-np
        resources:
          requests:
            memory: "64Mi"
            cpu: "20m"
          limits:
            memory: "128Mi"
            cpu: "100m"
#        livenessProbe:
#          httpGet:
#            path: /healthz
#            port: 8080
  
