apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: limitrange-np-operator-rolebinding-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: limitrange-np-operator-role-cluster
subjects:
  - kind: ServiceAccount
    name: limitrange-np-operator
    namespace: project-operator
