apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: limitrange-np-operator-role-cluster
rules:

  # Framework: knowing which other operators are running (i.e. peering).
  - apiGroups: [kopf.dev]
    resources: [clusterkopfpeerings]
    verbs: [list, watch, patch, get]

  # Framework: runtime observation of namespaces & CRDs (addition/deletion).
  - apiGroups: [apiextensions.k8s.io]
    resources: [customresourcedefinitions]
    verbs: [list, watch]
  - apiGroups: [""]
    resources: [namespaces]
    verbs: [list, watch]

  # Framework: admission webhook configuration management.
  - apiGroups: [admissionregistration.k8s.io/v1, admissionregistration.k8s.io/v1beta1]
    resources: [validatingwebhookconfigurations, mutatingwebhookconfigurations]
    verbs: [create, patch]
  # events   
  - apiGroups: [""]
    resources: [events]
    verbs: [create]


  # for controlling namespace  
  - apiGroups: ["*"]
    resources: [namespaces]
    verbs: [list, watch,patch,create,delete]
  - apiGroups: ["*"]
    resources: [namespaces/status]
    verbs: [list, watch,patch,create,delete]
  # for controlling limitranges  
  - apiGroups: ["*"]
    resources: [limitranges]
    verbs: [list, watch,patch,create,update,delete]
  # for controlling networkpolicies    
  - apiGroups: ["networking.k8s.io"]
    resources: [networkpolicies]
    verbs: [list, watch,patch,create,update,delete]
