apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: project-operator
  name: project-operator-rolebinding-namespaced
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: project-operator-role-namespaced
subjects:
  - kind: ServiceAccount
    name: project-operator