apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: chaos-operator
  name: chaos-operator-rolebinding-namespaced
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: chaos-operator-role-namespaced
subjects:
  - kind: ServiceAccount
    name: chaos-operator