apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: chaoses.djkormo.github
spec:
  group: djkormo.github
  names:
    kind: Chaos
    listKind: ChaosList
    plural: chaoses
    singular: chaos
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: true
    subresources:
      status: {}