apiVersion: apps/v1
kind: Deployment
metadata:
  name: primer-operator
  namespace: primer-operator
  labels:
    app: primer-operator
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: primer-operator
  template:
    metadata:
      labels:
        app: primer-operator
    spec:
      serviceAccountName: primer-operator
      securityContext:
        runAsUser:
          1000
      containers:
      - env:
        - name: VERBOSE
          value: "false"
        - name: DEBUG
          value: "false"
        - name: NAMESPACE
          value: ALL
        - name: LIVENESS
          value: "true"
        - name: LOOP_INTERVAL
          value: "30"
        - name: EXCLUDED_NAMESPACES
          value: "kube-system,kube-public,kube-node-lease"
        name: op
        image: djkormo/op-primer
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
