{{- if .Values.installCRDs -}}
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: shutdowns.djkormo.github
spec:
  group: djkormo.github
  names:
    kind: Shutdown
    listKind: ShutdownList
    plural: shutdowns
    singular: shutdown
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
        properties:
          spec:
            type: object
            properties:
              namespace:
                type: string
                nullable: false
              dry-run:
                type: boolean
                nullable: false
                default: false
              state:
                type: boolean
                nullable: false
                default: true
              deployments:
                type: boolean
                nullable: false
                default: false
              daemonsets:
                type: boolean
                nullable: false
                default: false
              statefulsets:
                type: boolean
                nullable: false
                default: false
              filter:
                type: string
                nullable: false
                default: "" 
              node-selector:
                type: string
                nullable: false
                default: "shutdown-non-existing"     
    served: true
    storage: true
    additionalPrinterColumns:
    - name: namespace
      type: string
      description: Namespace to control
      jsonPath: .spec.namespace
    - name: dry-run
      type: boolean
      description: Dry run mode. Default to false
      jsonPath: .spec.dry-run
    - name: state
      type: boolean
      description: State on - turning off, state off - turning on
      jsonPath: .spec.state
    - name: deployments
      type: boolean
      description: State on - turning off, state off - turning on
      jsonPath: .spec.deployments
    - name: statefulsets
      type: boolean
      description: State on - turning off, state off - turning on
      jsonPath: .spec.statefulsets
    - name: filter
      type: string
      description: Filtering resources to controll
      jsonPath: .spec.filter
  {{- end}}