apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: {{ .Values.namespace | default "default" }}
  name: {{ include "shutdown-operator.serviceAccountName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "shutdown-operator.serviceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "shutdown-operator.serviceAccountName" . }}