apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: restarter-operator
  name: restarter-operator-rolebinding-namespaced
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: restarter-operator-role-namespaced
subjects:
  - kind: ServiceAccount
    name: restarter-operator