name: Demoweb operator for DockerHub

on:
  push:
    paths:
      - 'kopf-example-demoweb-operator/**'
jobs:

  build:

    runs-on: ubuntu-latest
    env:
      APP_NAME: djkormo-op-demoweb

    steps:
    - uses: actions/checkout@v2

    - name: Publish to Docker Repository
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: djkormo/op-demoweb
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: Dockerfile
        workdir: kopf-example-demoweb-operator


