name: shutdown operator kubeval validate

on:
  push:
    paths:
      - 'kopf-example-shutdown-operator/**'

jobs:
  k8s-manifest-kubeval-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: validate manifests in kopf-example-shutdown-operator/deploy
        uses: instrumenta/kubeval-action@master
        with:
          files: kopf-example-shutdown-operator/deploy

  k8s-manifest-kubeval-helm-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Kubernetes tools
        uses: grebois/kube-tools@v1.5.2
        with:
          kubectl: 1.20.7
          kustomize: 3.5.5
          helm: 2.16.7
          helmv3: 3.2.1
          kubeseal: 0.12.5
          kubeaudit: 0.11.5
          command: |
            echo "Run kubeval for manifests"
            kubeval --strict --ignore-missing-schemas -d kopf-example-shutdown-operator/deploy/
            echo "Run kubeval for helm"
            helmv3 template kopf-example-shutdown-operator/helm | kubeval --strict --ignore-missing-schemas




