name: shutdown operator kubeval

on:
  push:
    paths:
      - 'kopf-example-shutdown-operator/**'

jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: validate manifests in kopf-example-shutdown-operator/deploy
        uses: instrumenta/kubeval-action@master
        with:
          files: kopf-example-shutdown-operator/deploy
#          token: ${{ secrets.GITHUB_TOKEN }}

