name: shutdown operator helm publish

on:
  push:
    paths:
      - 'kopf-example-shutdown-operator/**'

jobs:
  buildAndPublish:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v1
    - name: version
      run: echo ::set-output name=version::${GITHUB_REF/refs\/tags\//}
      id: version
    - name: build package
      working-directory: kopf-example-shutdown-operator/helm
#      run: helm package --version ${{ steps.version.outputs.version }} shutdown-operator
      run: helm package --version 0.1.0 shutdown-operator
    - name: create release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: ${{ steps.version.outputs.version }}
        tag_name: ${{ github.ref }}
        body_path: CHANGELOG.md
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: upload helm artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./kopf-example-shutdown-operator/helm/shutdown-operator-${{ steps.version.outputs.version }}.tgz
        asset_name: shutdown-operator-${{ steps.version.outputs.version }}.tgz
        asset_content_type: application/gzip
